/*
Directory cleaner file.

DO NOT EDIT THIS FILE.
To edit options, see '.build.js'
*/

const { rm } = require("fs/promises")

async function cleaner(options) {
	console.log(consoleColors.blue("CLEANING UP BUILD DIRECTORY..."))
	await rm(options.distDir, { recursive: true, force: true })
	console.log(consoleColors.green("SUCCESSFULLY CLEANED BUILD DIRECTORY"))
}

async function init(options) {
	console.log(consoleColors.white(" --------------- CLEANUP ---------------"))

	await cleaner(options)

	console.log(consoleColors.white(" ----------- CLEANUP FINISHED ----------"))
}

module.exports.init = init